name = "MatInt"
uuid = "f23b31af-f0ea-4208-b2e0-bbfc29c446c9"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.1"

[compat]
julia = "1"
StaticArrays = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
